version: "3.5"
services:
  vits:
    image: vits_fast_fine_tuning:latest
    ports: 
      - "6006:6006"
    volumes:
      - type: bind
        source: ./OUTPUT_MODEL
        target: /app/OUTPUT_MODEL
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]